Always return a promise from readthedocs.setup() (#204)
I followed Anthony's example from #202 to always return a Promise.

I knew there was a way to use `chai` via a plugin to test Promises. So,
I researched a little more about this and I found the exact plugin I've
seen before:
[`chai-as-promised`](https://www.chaijs.com/plugins/chai-as-promised/)

From the first example, you can see it's used to express exactly what
you wrote in a more simple way and providing some extra helpers.

I did a quick test to fail the check using a different error message and
it worked great:

```
tests/index.test.html:

 ❌ Main library > skip everything because Read the Docs Embed is present
      AssertionError: expected promise to be rejected with 'Error: Skip' but it was rejected with 'Error: Skipping injection'
      + expected - actual
      
      -Error: Skipping injection
      +Error: Skip
```

I like this pattern since it's pretty explicit and it uses the community
standards.